#!/usr/bin/env ruby
# coding: utf-8

if File.symlink?(__FILE__)
  path = File.dirname File.readlink(__FILE__)
else
  path = File.dirname File.expand_path(__FILE__)
end

require "#{path}/lib/player.rb"
require "#{path}/lib/playlist.rb"

def getch
  begin
    system("stty raw -echo")
    str = STDIN.getc
  ensure
    system("stty -raw echo")
  end
  return str
end

begin
  files = Dir.glob(ARGV[0]).sort_by { rand }
  raise if files.length == 0
rescue
  puts "Failed to load files."
  exit
end

$player       = Player.new
$playlist     = Playlist.new(files)

Thread.new do
  loop do
    case getch
      when 'p'
        $player.pause
      when 'q'
        $player.quit
        Kernel::exit
      when '.'
        $player.break
      when ','
        $player.break
        $playlist.prev!(2)
      when 'l'
        print `clear`
        print "#{$playlist.current_song}\n\r"
      else
        # probably accidental input; ignore
    end
  end
end

loop do
  $playlist.next!
  print "#{$playlist.current_song}\n\r"
  $player.play($playlist.current_file)
end
