#!/usr/bin/env ruby
# coding: utf-8

require 'lib/player.rb'
require 'lib/playlist.rb'

def getch
  begin
    system("stty raw -echo")
    str = STDIN.getc
  ensure
    system("stty -raw echo")
  end
  return str
end

begin
  files = Dir.glob(ARGV[0]).sort_by { rand }
  raise if files.length == 0
rescue
  puts "Failed to load files."
  exit
end

$player       = Player.new
$playlist     = Playlist.new(files)
$break        = false         # FIXME: implement breaking as a part of the Player class.

Thread.new do
  loop do
    case getch
      when 'p'
        $player.pause
      when 'q'
        $player.quit
        Kernel::exit
      when '.'
        $break = true
      when ','
        $break = true
        $p.prev!(2)
      else
        # probably accidental input; ignore
    end
  end
end

loop do
  print "#{File.basename($playlist.next!, ".mp3")}\n\r"
  $player.play($playlist.current)
end
