#!/usr/bin/env ruby
# coding: utf-8

require 'lib/player.rb'
require 'lib/playlist.rb'

def getch
  begin
    system("stty raw -echo")
    str = STDIN.getc
  ensure
    system("stty -raw echo")
  end
  return str
end

begin
  files = Dir.glob(ARGV[0]).sort_by { rand }
  raise if files.length == 0
rescue
  puts "Failed to load files."
  exit
end

$player       = Player.new
$playlist     = Playlist.new(files)
$break        = false         # FIXME: implement breaking as a part of the Player class.

Thread.new do
  loop do
    { 
      'p' => lambda { $player.pause               }, 
      'q' => lambda { $player.quit; Kernel::exit  },
      '.' => lambda { $break = true               },
      ',' => lambda { $break = true; $p.prev!(2)  }
    }[getch].call
  end
end

loop do
  print "#{File.basename($playlist.next!, ".mp3")}\n\r"
  $player.play($playlist.current)
end
